pages:
  names:
    '/' : Overview
    '[setup]' : Setup and Installation
    '[setup-prototypes]' : Prototypes and domains
    '[pages]' : Pages and URLs
    '[pages-order-ids]' : Ordering and assigning IDs
    '[pages-routing]' : Mapping URLs to Templates