debug: true

pages:
  titles:
    '/' : Overview
    '[setup]' : Setup and Installation
    '[setup-prototypes]' : Prototypes and domains
    '[pages]' : Pages and URLs
    '[pages-order-ids]' : Ordering and assigning IDs
    '[pages-routing]' : Routing URLs to pages
    '[pages-titles]' : Page titles
    '[pages-clean-urls]' : "Enabling 'clean' URLs"
    '[data-external]' : External data sources
    '[data-local]' : Local data files
    '[data-formats]' : Data formats
    '[data-fake]' : "Generating 'fake' data"
    '[data-twig]' : Template logic in data files  
    '[data-api]' : Data JSON API
    