timezone: Europe/London

debug: false

authenticate:
  password: 
  error: Your password was incorrect.
  ip_whitelist: # eg. 127.0.0.1
  
cookie:
  prefix: prototype-
  lifetime: 604800 # 1 week

triggers:
  data: _data
  shorturl: _p
  tools: _tools
  auth: _auth
  assets: _assets
  user: _user

user:
  identify: username
  auth: password
  login:
    redirect: /
    error: Your login details were incorrect.
  logout:
    redirect: /

pages:
  titles:
    '/' : 'Home'
  routes:
    # custom routes go here

cache:
  requests:
    expiry: 18000 # 5 mins
  
snippets:
  images:
    placeholder:
      service: dummyimage
      width: 200
      height: 200
      
data:
  csv:
    headers: true
    id_header: id
    escape: '\'
    delimiter: ','
    enclosure: '"'
    
