timezone: Europe/London

debug: false
sideload: true

authenticate:
  password: 
  error: Your password was incorrect.
  ip_whitelist: # eg. 127.0.0.1

storage:  
  adapter: cookie   # cookie or session 
  prefix: prontotype-
  lifetime: 604800 # 1 week

triggers:
  data: _data
  shorturl: _p
  tools: _tools
  auth: _auth
  assets: _assets
  files: _files  
  user: _user

user:
  config_file: users.yml
  identify: username
  auth: password
  login:
    redirect: /
    error: Your login details were incorrect.
  logout:
    redirect: /

pages:
  titles:
    '/' : 'Home'
  routes:
    # custom routes go here

cache:
  requests:
    expiry: 18000 # 5 mins
  
snippets:
  assets:
    placeholder:
      service: prontotype
      width: 200
      height: 200
      bgcolor: CCC
      color: 999
      category: abstract
      
data:
  faker:
    locale: en_EN
    seed: 
  csv:
    headers: true
    id_header: id
    escape: '\'
    delimiter: ','
    enclosure: '"'