system:
  cache:
    default_expiry: 18000
  snippets:
    images:
      placeholder:
        services:
          dummyimage: http://dummyimage.com/{{ width }}x{{ height }}/{{ bgcolor }}/{{ fgcolor }}/{{ format }}&text={{ text }}
          placeholdit: http://placehold.it/{{ width }}x{{ height }}/{{ bgcolor }}/{{ fgcolor }}/{{ format }}&text={{ text }}
          lorempixel: http://lorempixel.com/{{ width }}/{{ height }}/{{ category }}/{{ text }}



clean_urls: false

timezone: Europe/London

debug: false

authenticate:
  password: 
  error: Your password was incorrect.
  ip_whitelist: # eg. 127.0.0.1
  
cookie:
  prefix: prototype-
  lifetime: 604800 # 1 week

triggers:
  data: _data
  shorturl: _p
  tools: _tools
  auth: _auth
  assets: _assets
  user: _user

user:
  identify: username
  auth: password
  login:
    redirect: /
    error: Your login details were incorrect.
  logout:
    redirect: /

name_overrides:
  '/' : 'Home'

data:
  csv:
    headers: true
    delimiter: ','
    enclosure: '"'
    escape: '\'
    id_header: id

cache:
  requests:
    expiry: 18000 # 5 mins

routes:
  # "posts/(:all)" : "posts/post"

extensions:
  # example: ExampleExtension
  
snippets:
  images:
    placeholder:
      service: dummyimage
      width: 200
      height: 200