timezone: Europe/London

debug: false

authenticate:
  password: 
  error: Your password was incorrect.
  ip_whitelist: # eg. 127.0.0.1
  
cookie:
  prefix: prototype-
  lifetime: 604800 # 1 week

triggers:
  data: _data
  shorturl: _p
  tools: _tools
  auth: _auth
  assets: _assets
  user: _user

user:
  identify: username
  auth: password
  login:
    redirect: /
    error: Your login details were incorrect.
  logout:
    redirect: /

page_names:
  '/' : 'Home'

data:
  csv:
    headers: true
    delimiter: ','
    enclosure: '"'
    escape: '\'
    id_header: id

cache:
  requests:
    expiry: 18000 # 5 mins

routes:
  # "posts/(:all)" : "posts/post"

extensions:
  # example: ExampleExtension
  
snippets:
  images:
    placeholder:
      service: dummyimage
      width: 200
      height: 200